### ISSUE TITLE
relations

### ISSUE THREAD

**Issue by arademaker** [CLARIN-PL/Depracticated-WordnetLoom#7]
In the edit relations type, I can't add synset or sense relations.

In MacOS , branch Princeton. testing the editor.

**Comment by arademaker** [comment]
Some related error??

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.String cannot be cast to pl.edu.pwr.wordnetloom.sense.model.Sense
	at pl.edu.pwr.wordnetloom.client.systems.tooltips.SenseTooltipGenerator.getToolTipText(SenseTooltipGenerator.java:24)
	at pl.edu.pwr.wordnetloom.client.systems.tooltips.ToolTipList.getToolTipText(ToolTipList.java:200)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at pl.edu.pwr.wordnetloom.client.plugins.viwordnet.views.ViwnLexicalUnitRelationsViewUI.addRelation(ViwnLexicalUnitRelationsViewUI.java:276)
	at pl.edu.pwr.wordnetloom.client.plugins.viwordnet.views.ViwnLexicalUnitRelationsViewUI.actionPerformed(ViwnLexicalUnitRelationsViewUI.java:407)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
```
